### ISSUE TITLE
Release v1.0.0 on PyPi

### ISSUE THREAD

**Issue by kdeldycke** [pelican-plugins/similar-posts#6]
Now that the plugin is properly packaged in its `master` branch since https://github.com/pelican-plugins/similar-posts/pull/5 , here is the remaining tasks to have a proper v1.0.0 release on PyPi:

* [x] Rename `master` branch to `main`.
* [x] Sync repository description with the one from `pyproject.toml`.
* [x] Setup CI/CD by the way of GitHub workflows.
* [x] Release v1.0.0 first revision on PyPi.

**Comment by justinmayer** [comment]
Thanks for creating the follow-up issue, Kevin.

The primary branch is now `main`, and the repository description is in sync with `pyproject.toml`.

**Comment by justinmayer** [comment]
CI/CD should be all set up and ready to go.

@davidlesieur / @kdeldycke: I think we're all set to publish the first packaged release to PyPI. Any objections to me doing that now?

**Comment by davidlesieur** [comment]
No objections at all. Thanks @kdeldycke and @justinmayer for all this!

**Comment by kdeldycke** [comment]
Go go go for a release!

**Comment by justinmayer** [comment]
Version 1.0.0 has been published. Many thanks for all your work on this. It's been a pleasure collaborating with you. ✨  https://github.com/pelican-plugins/similar-posts/releases
